a=int(input())
b=int(input())
c=int(input())
d=int(input())
e=int(input())
f=int(input())
g=int(input())
h=int(input())
i=int(input())
j=int(input())
k=(a*b*c*d*e)
l=(f+g+h+i)
m=((k-l)*j)
print(k)
print(l)
print(m)
print("hasta la vista")